### ISSUE TITLE
I don't like your tone

### ISSUE THREAD

**Issue by mwheeler2** [mwheeler2/TBEP-Workshop-Exercise#1]
Fix it

**Comment by vmcongdon** [comment]
but how?? I need more direction...

**Comment by mwheeler2** [comment]
I think you still have some work on this issue.../

**Comment by mwheeler2** [comment]
I think you still have some work on this issue...

**Comment by vmcongdon** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/121889944/216389627-61c67e45-60ea-4fd5-b89f-bfffaefaf348.png)

**Comment by mwheeler2** [comment]
Great job!
